name: Simple FTP Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: FTP Deploy (envia tudo para /laravel)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTGATOR_FTP_HOST }}
          username: ${{ secrets.HOSTGATOR_FTP_USERNAME }}
            # Se usar SFTP troque password por privateKey e protocol: sftp
          password: ${{ secrets.HOSTGATOR_FTP_PASSWORD }}
          protocol: ftp
          # Pasta raiz (ex: /public_html) + /laravel/
          server-dir: ${{ secrets.HOSTGATOR_FTP_REMOTE_ROOT }}/laravel/
          timeout: 120000
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/storage/logs/**
            **/storage/framework/cache/data/**
            **/vendor/**.gitkeep
          log-level: standard
